# Generated by Django 5.1.5 on 2025-01-27 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
